### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by e-dub** [e-dub/pyAudioAnalyzer#1]
- [x] change name, pyAudioAnalysis is already out there, maybe pyAudioAnalyzer
- [x] add to pip
- [x] make open
- [ ] documentation
- [ ] add gui for recording
- [x] add Italian
